# Example running multiple laravel applications
# behind nginx-proxy for development
version: '3.6'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  example-web:
    image: lslio/nginx-php-fpm
    volumes:
      - ./web:/www
    environment:
      VIRTUAL_HOST: "example.localhost"
      SERVER_ROOT: "/www/public"

  example-api:
    image: lslio/nginx-php-fpm
    volumes:
      - ./api:/www
    environment:
      VIRTUAL_HOST: "api.example.localhost"
      SERVER_ROOT: "/www/public"